name: Caching and artifacts
on:
  workflow_dispatch:
jobs:
 use-axious:
    runs-on: ubuntu-latest:
        steps:
           - users: actions/checkout@v4
           - name: Install dependencies
             run: npm install
           - name: Use axios
             uses: actions/github-script@v6
             with:
                script: |
                 const axios = require('axios');
                 const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
                 console.log(res.data)
