name: download-repository
on:
  push:
    branches:
      - main
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: |
          echo "Listing repository contents after checkout:"
          ls -la
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: List files after checkout
        run: |
          echo "Listing repository contents after checkout:"
          ls -la