name: Dynamic Matrix
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: 'Node.js versions' 
        default: "14,15,16"
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-matrix
        with:
          script: "return {os: context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',')}"
          results-encoding: json
      - run: echo "${{steps.set-matrix.outputs.results}}"
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value 2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo "${{steps.step-1.outputs['step-output']}}"
          echo "${{steps.step-2.outputs['step-output']}}"

  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
 
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v