name: github events
on: 
  push:
    branches:
      - main
      - feature/feata
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - feature/feata
  issues:   
    types: [opened, closed, reopened]
jobs:
  github-events-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub event context
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4
    
