name: First Workflow
on:
  push:
    branches:
      - main

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run shell commands
        run: |
          echo "Starting the workflow..."
          echo "Current directory contents:"
          ls -la
          echo "Workflow completed."
      - name: Multiple commands
        run: |
          echo "GitHub Context:"
          echo "${{ toJson(github) }}"
          npm --version
          node --version
          
  parallel-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run parallel commands
        run: |
          echo "This is a parallel job running alongside the first job."
          date
          uname -a  
  dependent-job:
    needs: run-shell-commands
    runs-on: windows-latest
    steps:
      - name: Dependent job step
        run: |
          write-output "This job runs after the 'run-shell-commands' job is complete."
          write-output "All previous commands executed successfully."  
      - name: errorstep
        run: |
          doesnotexits
