name: manually triggered workflow
on:
  workflow_dispatch:
    inputs:
        stri:
            description: 'An example input for the manual workflow'
            required: false
            default: 'default value'
jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: manual job step
        run: |
          echo "This is a manually triggered workflow."
          echo "You can add your custom steps here."