name: manually triggered workflow
on:
    schedule:
      - cron: '0 0 * * 0'  # Runs every Sunday at midnight
jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: manual job step
        run: |
          echo "This is a manually triggered workflow."
          echo "You can add your custom steps here."