name: matrix workflow
on:
  push:
    branches:
      - main    
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        node-version: [14, 15, 16]
        os: [ubuntu-latest, windows-latest]
        includes:
          - os: ubuntu-latest  
            is-ubuntu: true
          - os: wmacos-latest
            node-version: 18
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: wubuntu-latest
            node-version: 14
     # max-parallel: 3
    runs-on: ${{ matrix.os }}
    
    steps:
      - run: node -v
      - run: echo "OS is ${{ toJson(matrix) }}"
      - uses: actions/setuo-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v