name: pull-request-target-comment
on:
  push:
   
    branches:
        - main
        - feature/feata
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
    branches:
        - main
        - feature/feata
jobs:
  pr-comment-job:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new pull request
        uses: actions/github-script@v6
        with:
            script: |
                github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: "Thank you for your pull request! We will review it shortly."
                })  