name: Using workflow templates
on:
 workflow_dispatch:
  inputs:
    name:
      description: 'Input description'
      type: string
      default: 'Ali'
      required: false


jobs:
 calling-reusable-workflow:
   uses: dragan-actions-course/workflows/.github/workflows/reusable.yaml@main
   with:
    name: ${{inputs.name}}
   secrets:
    access-token: ${{secrets.ACCESS_TOKEN}}
 calling-a-reusable-workflow-in-the-same-repo:
    uses: ./.github/workflows/resusable-workflow-output.yaml
 using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-workflow-in-the-same-repo
    steps:
     - run: echo ${{needs.calling-a-reusable-workflow-in-the-same-repo.outputs.date}}