name: Deploy PR branches
on:
  issue_comment:
    types: [created]
   
  pull_request_target:
    types: [created,opened]


jobs:
  trigger-pr-branch-deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: echo '${{toJson(github.event)}}'
      - run: echo '${{toJson(github.ref)}}'