name: status check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Run on failure
        if: failure()
        run: echo "This step runs only if previous steps have failed."
      - name: Runs on sucess
        if: success()           
        run: echo "Runs on sucess."
      - name: Always runs
        if: always()
        run: echo "This step always runs regardless of previous step outcomes."
      - name: Run on cancelled
        if: cancelled()
        run: echo "This step runs if the job was cancelled."
  job-2:    
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
       - run: echo "This step runs only if job-1 has failed."
