name: deploying app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    services:
       app:
         image: alialaa17/simple-node-api
        #  ports:
        #    - 3001:3000
         env:
           MONGO_HOSTNAME: mongo
       mongo: 
         image: mongo
        #  ports:
        #    - 27017:27017
    steps:
      - name: install curl
        run: apt-get update && apt-get install -y curl
      - name: Dump services context
        run: echo "{{ toJSON(job.services) }}"
      - name: Post a user
        run: 'curl -X POST http://app:3000/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address":dwded"}'''
      - name: Get all users
        run: curl http://app:3000/api/users
  
       