name: working with directory
on:
  push:
    branches:
      - main    
jobs:
  working-directory-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory contents
        run: |
          echo "Listing root directory contents:"
          ls -la /
          pwd

      - name: Change working directory and list contents
        run: |
          echo "Listing contents of the subdirectory:"
          ls -la .

      - name: Verify current working directory
        run: |
          echo "Current working directory:"
          pwd
  working-directory-windows:
    runs-on: windows-latest
    steps:
      - name: Display working directory contents
        run: |
          echo "Listing root directory contents:"
          ls .
          pwd

      